export const Counties = [
  'Co. Antrim',
  'Co. Armagh',
  'Co. Carlow',
  'Co. Cavan',
  'Co. Clare',
  'Co. Cork',
  'Co. Donegal',
  'Co.Down',
  'Co. Dublin',
  'Co. Fermanagh',
  'Co. Galway',
  'Co. Kerry',
  'Co. Kildare',
  'Co. Kilkenny',
  'Co. Laois',
  'Co. Leitrim',
  'Co. Limerick',
  'Co. Londonderry',
  'Co. Longford',
  'Co. Loth',
  'Co. Mayo',
  'Co. Meath',
  'Co. Monaghan',
  'Co. Offaly',
  'Co. Roscommon',
  'Co. Sligo',
  'Co. Tipperary',
  'Co. Tyrone',
  'Co. Waterford',
  'Co. Westmeath',
  'Co. Wexford',
  'Co. Wicklow',
];
